<a href="https://colab.research.google.com/github/singhm9283-bot/K-NN-/blob/main/deeplearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [222]:
# input layers k neurons me activation function nhi hota !!!!!!

# har neurons k do part hote hai----1) Linear fn  2) Activation fn
# 1) LF-sum of weights +bias       2) adds non linearity
# no of features is equal to no of neurons in input layer
# hidden layer me no of neurons 2to the power me hota hai

In [223]:
#from google.colab import files
#uploaded = files.upload()

In [224]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [225]:
df= pd.read_csv('cc_churn.csv')

In [226]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

ENCODING

In [227]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [228]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [229]:
df=pd.get_dummies(df,columns=['Gender','Geography'],drop_first=True)

In [230]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Male,Geography_Germany,Geography_Spain
0,1,15634602,Hargrave,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,2,15647311,Hill,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True
2,3,15619304,Onio,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,4,15701354,Boni,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,5,15737888,Mitchell,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True

FEATURES AND TARGET

In [231]:
X=df.drop(['RowNumber','CustomerId','Surname','Exited'],axis=1)
y=df['Exited']

In [232]:
X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Male,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,False,True
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,False,True

#

In [233]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

TRAINING , TESTING AND SCALING

In [234]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [235]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

NEURAL NETWORKS

In [236]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import Sequential # sequence layers banate hai jiske andr
# input or dense ate hain, dense mtlb hidden
from tensorflow.keras import Input
from tensorflow.keras.layers import Dense

In [237]:
model = Sequential()

In [238]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [239]:
# input layer
model.add(Input(shape=(11,))) # kuki 11 features hain by chacking X.shape()

# hidden layer 1
model.add(Dense(128,activation='relu'))

# hidden layer 2
model.add(Dense(64,activation='relu'))

# output
model.add(Dense(1,activation='sigmoid'))

In [240]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_27 (Dense)                │ (None, 128)            │         1,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,857 (38.50 KB)

 Trainable params: 9,857 (38.50 KB)

 Non-trainable params: 0 (0.00 B)

In [241]:
model.compile(loss='binary_crossentropy', metrics=['accuracy']) # mtlb ab model k architecture ban gaya hai
# bs ab train krege

In [242]:
earlystop=EarlyStopping(monitor= 'val_loss', patience=10, restore_best_weights=True)

In [243]:
# now we will train the model
model.fit(X_train, y_train,epochs=200, validation_data=(X_test,y_test), callbacks=earlystop)

Epoch 1/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8256 - loss: 0.4209 - val_accuracy: 0.8515 - val_loss: 0.3676
Epoch 2/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8522 - loss: 0.3640 - val_accuracy: 0.8540 - val_loss: 0.3490
Epoch 3/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8576 - loss: 0.3482 - val_accuracy: 0.8590 - val_loss: 0.3461
Epoch 4/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8572 - loss: 0.3431 - val_accuracy: 0.8560 - val_loss: 0.3454
Epoch 5/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8612 - loss: 0.3378 - val_accuracy: 0.8615 - val_loss: 0.3461
Epoch 6/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8624 - loss: 0.3351 - val_accuracy: 0.8635 - val_loss: 0.3433
Epoch 7/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8621 - loss: 0.3326 - val_accuracy: 0.8610 - val_loss: 0.3431
Epoch 8/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3287 - val_accuracy: 0.8635 - val_loss: 0.3460
Epoch 9/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8646 - loss: 0.3274 - val_accuracy: 0.8605 - val_loss: 0.3433
Epoch 10/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8640 - loss: 0.3249 - val_accuracy: 0.8595 - val_loss: 0.3464
Epoch 11/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8656 - loss: 0.3220 - val_accuracy: 0.8620 - val_loss: 0.3427
Epoch 12/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8671 - loss: 0.3202 - val_accuracy: 0.8560 - val_loss: 0.3459
Epoch 13/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8684 - loss: 0.3187 - val_accuracy: 0.8580 - val_loss: 0.3432
Epoch 14/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8684 - loss: 0.3163 - val_accuracy: 0.8620 - val_loss: 0.3476
Epoch 15/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8699 - loss: 0.3144 - val_accuracy: 0.8620 - val_loss: 0.3416
Epoch 16/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8694 - loss: 0.3115 - val_accuracy: 0.8535 - val_loss: 0.3465
Epoch 17/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8687 - loss: 0.3119 - val_accuracy: 0.8565 - val_loss: 0.3429
Epoch 18/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8704 - loss: 0.3090 - val_accuracy: 0.8580 - val_loss: 0.3562
Epoch 19/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8711 - loss: 0.3082 - val_accuracy: 0.8580 - val_loss: 0.3476
Epoch 20/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8715 - loss: 0.3069 - val_accuracy: 0.8575 - val_loss: 0.3495
Epoch 21/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8740 - loss: 0.3035 - val_accuracy: 0.8555 - val_loss: 0.3501
Epoch 22/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8712 - loss: 0.3034 - val_accuracy: 0.8595 - val_loss: 0.3493
Epoch 23/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8731 - loss: 0.3011 - val_accuracy: 0.8570 - val_loss: 0.3484
Epoch 24/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8729 - loss: 0.3000 - val_accuracy: 0.8570 - val_loss: 0.3507
Epoch 25/200
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8766 - loss: 0.2980 - val_accuracy: 0.8555 - val_loss: 0.3532

In [244]:
y_pred = model.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [245]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred.round()))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1607
           1       0.70      0.52      0.60       393

    accuracy                           0.86      2000
   macro avg       0.80      0.73      0.76      2000
weighted avg       0.85      0.86      0.85      2000