<a href="https://colab.research.google.com/github/singhm9283-bot/K-NN-/blob/main/Knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

k-nn

In [4]:
#from google.colab import files
#uploaded = files.upload()

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [6]:
df= pd.read_csv('Fish.csv')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Species  159 non-null    object
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB

In [8]:
df['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [9]:
df.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

SOME WEIGHTS ARE 0 SO NEED TO BE HANDLED

In [10]:
df['Weight']=df['Weight'].replace(0,np.nan)

In [11]:
df['Weight']=df['Weight'].fillna(df['Weight'].mean())

In [12]:
df.describe()

            Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    400.847468   26.247170   28.415723   31.227044    8.970994    4.417486
std     356.564044    9.996441   10.716328   11.610246    4.286208    1.685804
min       5.900000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     122.500000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     290.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

FEATURE AND TARGET DEFINING...

In [13]:
X=df.drop('Species',axis=1)
X.head()

   Weight  Length1  Length2  Length3   Height   Width
0   242.0     23.2     25.4     30.0  11.5200  4.0200
1   290.0     24.0     26.3     31.2  12.4800  4.3056
2   340.0     23.9     26.5     31.1  12.3778  4.6961
3   363.0     26.3     29.0     33.5  12.7300  4.4555
4   430.0     26.5     29.0     34.0  12.4440  5.1340

In [14]:
y=df['Species']
y.head()

0    Bream
1    Bream
2    Bream
3    Bream
4    Bream
Name: Species, dtype: object

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
accuracy_list = []

In [27]:
from sklearn.metrics import accuracy_score

In [36]:
for i in range(1, 11):

  knn = KNeighborsClassifier(n_neighbors = i)

  knn.fit(X_train, y_train)

  # Finding the Predicted Values of the KNN Model

  y_prediction = knn.predict(X_test)

  # Finding the Accuracy

  accuracy_score(y_test, y_prediction)
  accuracy_list.append(accuracy_score(y_test, y_prediction))

RANDOM FOREST

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
model=RandomForestClassifier(n_estimators=100)

In [21]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [22]:
y_pred=model.predict(X_test)

In [31]:
accuracy_score(y_test, y_pred)

0.8125

In [ ]:
# hyperparamters are used in ml models to determine model performane are r defined before training