<a href="https://colab.research.google.com/github/singhm9283-bot/K-NN-/blob/main/smote.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
#from google.colab import files
#
uploaded= files.upload()

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
df= pd.read_csv('diabetes.csv')

In [33]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [34]:
X=df.drop('Outcome', axis=1)
y= df['Outcome']

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=42)

In [36]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

SMOTE

In [37]:
from imblearn.over_sampling import SMOTE
oversampling = SMOTE(sampling_strategy='auto', k_neighbors=3,random_state=42)

In [38]:
X_train, y_train= oversampling.fit_resample(X_train, y_train)

In [39]:
y_train.value_counts()

Outcome
0    401
1    401
Name: count, dtype: int64